DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  email VARCHAR(255),
);


DROP TABLE IF EXISTS student;

CREATE TABLE student (
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  summary VARCHAR(255),
  image VARCHAR(255),
  is_saved BOOLEAN
);


DROP TABLE IF EXISTS company;

CREATE TABLE company (
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  summary VARCHAR(255),
  image VARCHAR(255),
  is_saved BOOLEAN
);